-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 11:18:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Post_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Post_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Post_db` DEFAULT CHARACTER SET utf8 ;
USE `Post_db` ;

-- -----------------------------------------------------
-- Table `Post_db`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Post_db`.`Post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(270) NULL,
  `path_img` VARCHAR(150) NULL,
  `user` VARCHAR(45) NULL,
  `date` DATE NULL,
  `topic` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Post_db`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Post_db`.`Comment` (
  `idComment` INT NOT NULL,
  `message` VARCHAR(270) NULL,
  `id_post` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idComment`, `id_post`),
  INDEX `fk_Comentario_Publicacion_idx` (`id_post` ASC),
  CONSTRAINT `fk_Comentario_Publicacion`
    FOREIGN KEY (`id_post`)
    REFERENCES `Post_db`.`Post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* Populate database with test posts */

insert into post (message, path_img, user, topic, title) values ("msg1", "path1", "user1", "topic1", "title1");
insert into post (message, path_img, user, topic, title) values ("msg2", "path2", "user2", "topic2", "title2");
insert into post (message, path_img, user, topic, title) values ("msg3", "path3", "user3", "topic3", "title3");
insert into post (message, path_img, user, topic, title) values ("msg4", "path4", "user4", "topic4", "title4");
insert into post (message, path_img, user, topic, title) values ("msg5", "path5", "user5", "topic5", "title5");