package GUIs;

import DTO.Post;
import ServerAndClient.ForumClient;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author Absalom Herrera
 */
public class ClientMainGUI extends javax.swing.JFrame {

    private String user;

    /**
     * Creates new form ClientMainGUI
     */
    public ClientMainGUI(String user) {
        this.setTitle(" - Discussion Forum - ");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.user = user;
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
        }
        this.pack();
        this.setLocationRelativeTo(null);
        welcomeLabel.setText("Welcome " + user + "!");
        loadWindowHTML();
        // We call this method to obtain 
        //getAllPost();
    }

    public void loadWindowHTML() {
        editorPane.setEditable(false);
        HTMLEditorKit kit = new HTMLEditorKit();
        editorPane.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule("body{background-color: #87CEFA;}");
        styleSheet.addRule("h1,h3 {font-family: Arial, Helvetica, sans-serif; color: white;}");
        String htmlString = "<!DOCTYPE html>\n" +
"<html>\n" +
"<head>\n" +
"	<title>Discussion Forum</title>\n" +
"	<meta charset=\"utf-8\">\n" +
"	<style type=\"text/css\">\n" +
"		body{\n" +
"			background-color: #87CEFA;\n" +
"		}\n" +
"		h1,h3{\n" +
"			font-family: Arial, Helvetica, sans-serif;\n" +
"			color: white;\n" +
"		}\n" +
"	</style>\n" +
"</head>\n" +
"<body>\n" +
"	<h1 align=\"center\">Discussion Forum</h1>\n" +
"    <h3 align=\"center\">Post Here</h3>\n" +
"</body>\n" +
"</html>";
        Document doc = kit.createDefaultDocument();
        editorPane.setDocument(doc);
        editorPane.setText(htmlString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        createPostButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        createPostButton.setText("Create Post");
        createPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPostButtonActionPerformed(evt);
            }
        });

        scrollPane.setViewportView(editorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(createPostButton))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logoutButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addGap(90, 90, 90)
                .addComponent(logoutButton)
                .addGap(30, 30, 30)
                .addComponent(createPostButton)
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void createPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPostButtonActionPerformed
        CreatePostGUI cpg = new CreatePostGUI(user);
        cpg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createPostButtonActionPerformed

    private void getAllPost() {
        ForumClient fc = new ForumClient();
        List l = null;
        l = fc.getAllPost();
        if (l != null) {
            for (int i = 0; i < l.size(); i++) {
                Post p = (Post) l.get(i);
                System.out.println(p.toString());
            }
        } else {
            System.err.println("NULL POSTS");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPostButton;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JButton logoutButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
