/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import DAO.ForumDAO;
import DTO.Comment;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.ListModel;

/**
 *
 * @author Carlo
 */
public class CommentGUI extends javax.swing.JFrame {

    /**
     * Creates new form CommentGUI
     */
    JLabel comments_lbl[];
    List comments;
    int idPost;
    String user;
    DefaultListModel<String> model;
    public CommentGUI(List comments, int idPost, String user) {
        this.idPost = idPost;
        initComponents();
        this.user = user;
        this.comments = comments;
        model = new DefaultListModel<>();
        if(comments != null) {
            comments_lbl = new JLabel[comments.size()];
            
            for(int i = 0; i < comments.size(); i++) {
                Comment current = (Comment)(comments.get(i));
                System.out.println(current.toString());
                comments_lbl[i] = new JLabel(current.toString());
                comments_lbl[i].setSize(500, 80);
                model.addElement(current.toString());
            }
            jList1.setModel(model);
            jList1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addcomment_btn = new javax.swing.JButton();
        comment_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        addcomment_btn.setText("Add comment");
        addcomment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcomment_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comment_txt)
                    .addComponent(addcomment_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comment_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addcomment_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcomment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcomment_btnActionPerformed
        ForumDAO fd = new ForumDAO();
        Comment comment = new Comment();
        comment.setDate(null);
        
        //Comment actual = (Comment)(comments.get(0));
        int id_post = this.idPost;
        
        comment.setId_post(id_post);
        comment.setMessage(comment_txt.getText());
        comment.setUser(user);
        model.addElement(comment.toString());
        jList1.setModel(model);
        jList1.revalidate();
        try {
            fd.createComment(comment);
        } catch (SQLException ex) {
            Logger.getLogger(CommentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addcomment_btnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcomment_btn;
    private javax.swing.JTextField comment_txt;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
